use_frameworks!

platform :ios, '10.0'

target 'LibEx_Example' do
  pod 'LibEx', :path => '../'

  target 'LibEx_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
